In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib


def generate_dgp(COUNT, suffix, n_samples, d, epsilon_o, tau, eta_2):
    # Covariates and weights
    X = np.random.uniform(-3, 3, size=(n_samples, d))
    w_s = np.random.uniform(1, 20, size=d)
    w_c = np.random.uniform(1, 20, size=d)
    
    w_i_s = np.random.choice([1, 2], size=d)
    w_i_c = np.random.choice([1, 2], size=d)
    
    # Nonlinear transformation
    z = np.sum(np.sin(w_i_s*X) * w_s + np.cos(w_i_c*X) * w_c, axis=1)

    # Normalization to [0, 100]
    z_min = -np.sum(w_s + w_c)
    z_max = np.sum(w_s + w_c)
    f = ((z - z_min) / (z_max - z_min)) * 30
    t_E = f.astype(int) + np.random.randint(0, eta_2, n_samples)
    
    # Censoring indicator
    eta = np.random.uniform(-1*epsilon_o, epsilon_o, size=n_samples)
    e = (1/(1 + np.exp(-X.reshape(-1) + eta)) > tau).astype(int)
    print(e)
    
    # Observed time
    delta = np.random.uniform(0, f)
    t_obs = np.where(e == 0, f - delta, t_E)
    t_obs = t_obs.astype(int)
    
    idxs = np.random.permutation(n_samples)

    X_train = X[idxs[:len(idxs)//3]]
    orig_y_train = t_E[idxs[:len(idxs)//3]]
    y_train = t_obs[idxs[:len(idxs)//3]]
    binary_y_train = e[idxs[:len(idxs)//3]]

    X_val = X[idxs[len(idxs)//3: 2*len(idxs)//3]]
    orig_y_val = t_E[idxs[len(idxs)//3: 2*len(idxs)//3]]
    y_val = t_obs[idxs[len(idxs)//3: 2*len(idxs)//3]]
    binary_y_val = e[idxs[len(idxs)//3: 2*len(idxs)//3]]
    
    X_test = X[idxs[2*len(idxs)//3:]]
    orig_y_test = t_E[idxs[2*len(idxs)//3:]]
    y_test = t_obs[idxs[2*len(idxs)//3:]]
    binary_y_test = e[idxs[2*len(idxs)//3:]]

    joblib.dump(X_train, '/data4/meerak/viol4_onevar_data/X_train_%s.joblib'%(suffix))
    joblib.dump(orig_y_train, '/data4/meerak/viol4_onevar_data/orig_y_train_%s.joblib'%(suffix))
    joblib.dump(y_train, '/data4/meerak/viol4_onevar_data/y_train_%s.joblib'%(suffix))
    joblib.dump(binary_y_train, '/data4/meerak/viol4_onevar_data/binary_y_train_%s.joblib'%(suffix))

    joblib.dump(X_val, '/data4/meerak/viol4_onevar_data/X_val_%s.joblib'%(suffix))
    joblib.dump(orig_y_val, '/data4/meerak/viol4_onevar_data/orig_y_val_%s.joblib'%(suffix))
    joblib.dump(y_val, '/data4/meerak/viol4_onevar_data/y_val_%s.joblib'%(suffix))
    joblib.dump(binary_y_val, '/data4/meerak/viol4_onevar_data/binary_y_val_%s.joblib'%(suffix))
    
    
    joblib.dump(X_test, '/data4/meerak/viol4_onevar_data/X_test_%s.joblib'%(suffix))
    joblib.dump(orig_y_test, '/data4/meerak/viol4_onevar_data/y_test_%s.joblib'%(suffix))
    joblib.dump(binary_y_test, '/data4/meerak/viol4_onevar_data/actual_binary_y_test%s.joblib'%(suffix))
    
    if sum(binary_y_train) == 0 or sum(binary_y_train) == len(binary_y_train) or sum(binary_y_val) == 0 or sum(binary_y_val) == len(binary_y_val):
        print('ERROR')
    


d = 1
n_samples = 10000

f = open('viol4_dgp_params.txt', 'w')

for COUNT in range(1000):
    epsilon_o = np.random.choice([0.1, 0.5, 1], 1)[0]
    tau = np.random.choice([0.5, 0.7, 0.9], 1)[0]
    eta_2 = np.random.choice([5, 10], 1)[0]
    suffix = 'COUNT%d'%(COUNT)
    generate_dgp(COUNT, suffix, n_samples, d, epsilon_o, tau, eta_2)
    f.write('%0.2f, %0.2f, %0.2f\n'%(epsilon_o, tau, eta_2))



[1 1 0 ... 0 1 1]
[0 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[0 1 1 ... 1 1 0]
[1 0 1 ... 0 0 1]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 1 1]
[1 0 1 ... 1 1 0]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 1]
[1 0 0 ... 0 0 0]
[1 1 0 ... 1 0 0]
[1 1 1 ... 1 0 0]
[1 0 0 ... 0 0 0]
[0 1 0 ... 0 0 0]
[1 0 1 ... 0 0 0]
[0 1 0 ... 0 0 0]
[1 1 1 ... 0 0 1]
[0 0 0 ... 1 0 0]
[0 1 0 ... 1 0 1]
[0 0 0 ... 0 0 0]
[0 0 0 ... 1 0 0]
[0 0 1 ... 1 0 0]
[0 0 0 ... 0 0 0]
[0 1 1 ... 0 0 0]
[0 0 0 ... 1 1 1]
[1 0 1 ... 0 1 0]
[1 0 0 ... 1 1 0]
[0 0 0 ... 0 0 0]
[0 1 1 ... 1 1 1]
[0 1 1 ... 0 0 1]
[1 0 1 ... 1 0 1]
[1 1 1 ... 0 0 1]
[0 1 0 ... 0 0 1]
[0 1 1 ... 0 1 1]
[1 0 0 ... 0 0 1]
[0 0 0 ... 0 0 0]
[0 1 1 ... 0 1 0]
[1 1 0 ... 0 1 0]
[0 0 0 ... 0 1 0]
[0 0 1 ... 0 0 1]
[1 1 0 ... 0 1 0]
[0 0 0 ... 1 1 0]
[0 0 0 ... 1 0 0]
[0 0 0 ... 0 0 0]
[1 1 0 ... 1 0 0]
[1 0 1 ... 1 0 0]
[0 0 0 ... 1 0 1]
[1 0 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
[0 1 0 ... 0 0 0]
[0 1 1 ... 0 1 0]
[0 1 0 ... 0 0 1]
[1 1 1 ... 1 1 0]
[0 1 1 ... 0 1 1]
[1 1 1 ...

In [2]:
COUNT

999